### ISSUE TITLE
第一次push卡顿

### ISSUE THREAD

**Issue by popor** [yxh265/YYRouter#1]
由于没有提供一个合适的加载所有url的接口, 导致用户第一次点击按钮跳转, 会延迟0.5秒才能生效. 从你的demo中也可以感觉出来.

**Comment by yxh265** [comment]
因为我代码里面写了这个。

你可以搜搜来看看，目的是判断路由的定义是否合法。

`#if DEBUG
    /// 自动检查所有的路由设置是否符合规范，当发现不符合规范的路由设置，直接中断
`



正常release的代码不做debug检查就不会卡

然后这里有几个地方不好的，我也做了优化，THX

**Comment by yxh265** [comment]
已经优化。当找不到路由的时候才检查，提高调试速度

**Comment by yxh265** [comment]
close
